feat: dockerfile
borisdayma/dalle-mini pull request #191
Opened 2022-05-21 20:34 UTC by batrlatom

2022-05-22 12:31 UTC, Saibamen commented on Docker/Dockerfile
> +WORKDIR /workspace
```suggestion
FROM nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04

RUN apt-get update && apt-get install -y \
  git \
  python3 \
  python3-pip \
  && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html \
  && pip install -q \
  git+https://github.com/borisdayma/dalle-mini.git \
  git+https://github.com/patil-suraj/vqgan-jax.git

WORKDIR /workspace

```

2022-05-22 12:31 UTC, Saibamen requested changes
```suggestion
FROM nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04

RUN apt-get update && apt-get install -y \
  git \
  python3 \
  python3-pip \
  && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html \
  && pip install -q \
  git+https://github.com/borisdayma/dalle-mini.git \
  git+https://github.com/patil-suraj/vqgan-jax.git

WORKDIR /workspace

```

Use dockerfile best practices: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get

2022-05-23 15:30 UTC, borisdayma commented
Many thanks!
Is it ready to be merged?

2022-05-24 11:26 UTC, batrlatom commented
The dockerfile was intented to be just a environment for development and inference. If you want to have for example gradio or streamlit app to be run after the start, I can make it so.

2022-05-30 16:52 UTC, merged